### ISSUE TITLE
errors when use Multiple GPUs training 

### ISSUE THREAD

**Issue by 4C79** [MyuLi/SST#7]
the error likes:
ModuleNotFoundError: No module named 'models.sync_batchnorm'
请问这个模块需要install 还是？

**Comment by MyuLi** [comment]
如果需要用多GPU之间的BatchNorm，你可以去这个链接下载一下，[link](https://github.com/vacancy/Synchronized-BatchNorm-PyTorch)。如果不需要用BatchNorm，应该可以直接删掉相关import语句
